<?php
declare(strict_types=1);

use PHPUnit\Framework\TestCase;
use libs\RemoveDuplicates;

class RemoveDuplicatesTest extends TestCase
{
    private $dataFile;

    public function setUp()
    {
        $this->dataFile = __DIR__.'/../fixtures/email_list.json';
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function testFilterRemoveDuplicates() {
        $email_list = json_decode(file_get_contents($this->dataFile), true);
        echo "\n Size of the list: " . sizeof($email_list) ."\n";

        $start_time = microtime(true);
        $unique_list = RemoveDuplicates::filter($email_list);
        echo "\n Size of unique list: ". sizeof($unique_list) ."\n";
        $end_time = microtime(true);
        $elp_time = $end_time - $start_time;
        $this->assertTrue($elp_time < 1);
    }
}